### ISSUE TITLE
Medication review codelist needs review

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/medication-reviews#12]
Just having a quick look through. There are a few codes I used regularly which don't seem to be included.
- 314530002 | Medication review done (situation)
- 719329004 | Medication review done by pharmacist (situation)

In particular 314530002 | Medication review done (situation) is build in to TPP as preferred code to use when reviewing meds so important to include.

**Comment by speed-vm** [comment]
### Review of medication review codelists
**Current Medication Review Codelist**
**Care Planning Medication Simple Reference Set NHS Digital**
opensafely/care-planning-medication-review-simple-reference-set-nhs-digital/61b13c39
According to SNOMED CT browser this is now inactive.
This codelist includes disease specific reviews

**Alternative is NHSD MEDRVW_COD**
https://www.opencodelists.org/codelist/nhsd-primary-care-domain-refsets/medrvw_cod/20200812
This is a more up to date codelist appearing on the NHSD browser. 
Parent term is Procedure carried out on patient' and child term is medication review done.

For comparison:
https://www.opencodelists.org/codelist/nhsd-primary-care-domain-refsets/medrvw_cod/20200812/diff/61b13c39/

Suggest inclusion of the up to date NHSD codelist rather than older version. 
Breakdown by individual codelist might be interesting to see differences in profession.

![image](https://user-images.githubusercontent.com/77046757/189911775-536962e5-b770-45f1-8d26-68e3e2c3545f.png)

**Previous discussion on this regarding SRO project:**
[(https://github.com/opensafely/SRO-smr/issues/14)]
Outcome appears to have been to combine the general lists and report SMR separately.

**Comment by speed-vm** [comment]
https://github.com/opensafely/codelist-development/issues/245 

Discussion about medication review codelists and usage is in this issue. We have used the REFSET and then reviewed other codes which have high usage but are not included in this refset. Details of those included and excluded can be found in the issue in the codelist development repo.
