### ISSUE TITLE
Medication review codelist

### ISSUE THREAD

**Issue by speed-vm** [opensafely/medication-reviews#6]
Hi Louis and Chris, 
I cannot seem to get the generic medication review codelist to run properly (not SMR).... please may you have a look when you have chance. I'm sorry it is probably something silly. 
Thanks

**Comment by chrisjwood16** [comment]
@speed-vm The issue is with [this line](https://github.com/opensafely/medication-reviews/blob/VS_plot_develop/analysis/codelists.py#L33):

"opensafely/care-planning-medication-review-simple-reference-set-nhs-digital.csv"
Should be
"codelists/opensafely-care-planning-medication-review-simple-reference-set-nhs-digital.csv"
